# These are supported funding model platforms

github: ['tamddk']
patreon: -
open_collective: -
ko_fi: sodik
tidelift: -
community_bridge: -
liberapay: -
issuehunt: -
otechie: -
lfx_crowdfunding: -
custom: ['https://app.midtrans.com/payment-links/1685538081797', 'https://app.midtrans.com/payment-links/1685538150873', 'https://app.midtrans.com/payment-links/1685538218384']
